name: ual-geoblacklight
proxy:
  appserver:
    - local-dev.library.arizona.edu
  solr:
    - solr.lndo.site:8983
services:
  appserver:
    type: lando
    ssl: true
    sslExpose: false
    services:
      build:
        context: .
        dockerfile: ./docker/app/Dockerfile
      command: bash -c "set -e && shibd -f & exec apache2ctl -DFOREGROUND"
      volumes:
        - ./docker/app/conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
        - ./docker/app/sp/attribute-map.xml:/etc/shibboleth/attribute-map.xml
        - ./docker/app/sp/attribute-policy.xml:/etc/shibboleth/attribute-policy.xml
        - ./docker/app/sp/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml
      environment:
        SOLR_URL: "http://solr:8983/solr/blacklight-core/"
    build:
      - bin/rails db:migrate RAILS_ENV=development
  solr:
    type: solr:9.6
    core: blacklight-core
    config:
      dir: ./solr/conf

tooling:
  rails:
    service: appserver
    cmd: bundle exec rails
  bundle:
    service: appserver
  rake:
    service: appserver
  cap:
    service: appserver
  fgdc2json:
    service: appserver
    cmd: bash -c "cd /app/scripts/fgdc2json && ruby run.rb"
