name: ual-geoblacklight
proxy:
  appserver:
    - local-dev.library.arizona.edu:3000
  solr:
    - solr.lndo.site:8983
services:
  appserver:
    type: compose
    ssl: true
    services:
      build:
        context: .
        dockerfile: ./docker/app/Dockerfile
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 'ssl://0.0.0.0:3000?key=/app/config/ssl/local_dev_library_arizona_edu.key&cert=/app/config/ssl/local_dev_library_arizona_edu.crt'"
      environment:
        SOLR_URL: "http://solr:8983/solr/blacklight-core/"
    build:
      - bundle install --gemfile=/app/Gemfile
      - bin/rails db:migrate RAILS_ENV=development
  solr:
    type: solr:9.6
    core: blacklight-core
    config:
      dir: ./solr/conf

tooling:
  rails:
    service: appserver
    cmd: bundle exec rails
  bundle:
    service: appserver
  rake:
    service: appserver
  cap:
    service: appserver
